plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://reasoning-machine.github.io
baseurl: /grok

title: Reasoning Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Reasoning-Machine
  verb: Reasoning
  instructions_file: reasoning.txt
  token: grok.txt
  apiUrl: https://api.x.ai/v1/chat/completions

app:
  worker_name: grokapi.js

lm:
  model: grok-3-mini
  max_completion_tokens: 8192
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95
  reasoning_effort: high


github_settings:
  owner: reasoning-machine
  repo: reasoning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
